# Generated by Django 5.2.1 on 2025-05-31 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tweet',
            old_name='test',
            new_name='text',
        ),
    ]
